# Generated by Django 6.1.1 on 2026-10-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0003_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='numero_prestamo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
