# Generated by Django 6.1.1 on 2026-10-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0004_prestamo_numero_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='tipo_prestamo',
            field=models.CharField(choices=[('cuotas', 'Capital + intereses en cuotas'), ('solo_intereses', 'Solo intereses')], default='cuotas', max_length=20),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='frecuencia',
            field=models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('quincenal', 'Cada 15 días'), ('mensual', 'Mensual')], max_length=10),
        ),
    ]
