# Generated by Django 6.1.1 on 2026-10-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0005_prestamo_tipo_prestamo_alter_prestamo_frecuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('nequi', 'Nequi')], max_length=10, null=True),
        ),
    ]
